### ISSUE TITLE
for shashiee817 @ 2023-09-29 00:25:57 UTC

### ISSUE THREAD

**Issue by shashiee817** [coinbase/waas-sdk-react-native#65]
Review Error for shashiee817 @ 2023-09-29 00:25:57 UTC
User must have write permissions to review

_Originally posted by @cb-heimdall in https://github.com/coinbase/waas-sdk-react-native/issues/37#issuecomment-1740154677_

**Comment by shashiee817** [comment]
> ```
>           Review Error for shashiee817 @ 2023-09-29 00:25:57 UTC
> ```
> 
> 
>     
>   
> 
> User must have write permissions to review
> 
> 
> _Originally posted by @cb-heimdall in [#37 (comment)](https://github.com/coinbase/waas-sdk-react-native/pull/37#issuecomment-1740154677)_

<details><summary>Details</summary>
<p>

/

</p>
</details>

**Comment by MichealSD13** [comment]
[4ff17837-7432-4d3c-a52e-ef5637c047e7 (1).zip](https://github.com/coinbase/waas-sdk-react-native/files/13706354/4ff17837-7432-4d3c-a52e-ef5637c047e7.1.zip)
