### ISSUE TITLE
Project 1

### ISSUE THREAD

**Issue by Agilan989** [coinbase/waas-sdk-react-native#68]

**Comment by DanielaDudyova** [comment]
Heloo

**Comment by Erslisz** [comment]
Hi

**Comment by DanielaDudyova** [comment]
why can't I use coinbase, I can't buy or sell, I can't keep giving my passport and citizenship, I have new documents

**Comment by DanielaDudyova** [comment]
Hi

**Comment by Erslisz** [comment]
Your going to have to call them
