### ISSUE TITLE
A.T.COL.MUNDIAL.COM Company ID 9130357469609216 Manage 

### ISSUE THREAD

**Issue by 31031969** [coinbase/waas-sdk-react-native#78]
[LICENSE omar alfonso rodriguez borja.txt](https://github.com/coinbase/waas-sdk-react-native/files/14089458/LICENSE.omar.alfonso.rodriguez.borja.txt)
[omar72158895-gold-pai-pay_31031969_1ab3853c069c7db6c12f1937f9c632d21283f08e.json](https://github.com/coinbase/waas-sdk-react-native/files/14089460/omar72158895-gold-pai-pay_31031969_1ab3853c069c7db6c12f1937f9c632d21283f08e.json)
[omar721588951.json](https://github.com/coinbase/waas-sdk-react-native/files/14089464/omar721588951.json)
[35425669 (3) (1).pdf](https://github.com/coinbase/waas-sdk-react-native/files/14089465/35425669.3.1.pdf)
[1 (1) (1) (1) (2) (2) (1).pdf](https://github.com/coinbase/waas-sdk-react-native/files/14089466/1.1.1.1.2.2.1.pdf)

**Comment by DanielaDudyova** [comment]
hi what is it
